declare module '@env' {
  export const FIREBASE_API_KEY: string;
  export const FIREBASE_AUTH_DOMAIN: string;
  export const FIREBASE_PROJECT_ID: string;
  export const FIREBASE_STORAGE_BUCKET: string;
  export const FIREBASE_MESSAGING_SENDER_ID: string;
  export const FIREBASE_APP_ID: string;
  export const FIREBASE_DATABASE_URL: string;
  export const BACKEND_URL: string;
  export const APPOINTMENT_RESERVATION_FEE: string;
  export const ENABLE_SERVICE_PAYMENT_ONLINE: string;
  export const GST_TAX_RATE: string;
  export const CONVENIENCE_FEE: string;
  export const RAZORPAY_KEY: string;
  export const RAZORPAY_SECRET: string;
  export const GOOGLE_IOS_CLIENT_ID: string;
  export const GOOGLE_ANDROID_CLIENT_ID: string;
  export const GOOGLE_WEB_CLIENT_ID: string;
  export const FACEBOOK_APP_ID: string;
  export const FACEBOOK_APP_NAME: string;
  export const FACEBOOK_DISPLAY_NAME: string;
  export const APPLE_SERVICE_ID: string;
}
